apiVersion: v1
kind: PersistentVolume
metadata:
  name: anton-nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs
    server: 192.168.1.99

