apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-1g
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi 
  storageClassName: ""
  volumeName: anton-nfs
